### ISSUE TITLE
Question about the goal of this project

### ISSUE THREAD

**Issue by gtf35** [RikkaApps/Sui#1]
Root itself is a concept in Linux, coincidentally, Android is running on Linux.

> The goal of this project is to replace the "su" executable and call for the root community to switch to the correct way.

The purpose of this project seems to be to call system APIs in an efficient way.

 It is not related to su, no need to replace it.

> The result is, everyone suffers from "su".

「su」 is very convenient in some simple scenarios, such as move or delete certain files, set permissions

By the way, this is a very interesting project, I love it. It can be of great help in complicated situations.😉

**Comment by RikkaW** [comment]
All my views are from the perspective of developing an Android application that requires root, using "su" is indeed painful.

The "su" binary itself is also "just an interface", this project is to replace this interface, not the real thing behinds it.

For the user, nothing will change. There is already an API, `IRemoteProcess newProcess(String[] cmd, String[] env, String dir)`, which allows the app to create a "shell". It is easy for the terminal app to switch to the new way. For using "su" in ADB, simply copy the original "su" file to somewhere like `/data/local/tmp`.

**Comment by gtf35** [comment]
I feel that the description in the document is too extreme, but this situation does exist.

- If only one command, so easy 😆

- If I need more than one line of commands, it will be hard to use.😒

- If there is a correlation between the two commands, emmm, kill me please....😢

SU is really not suitable for Android,  he is very suitable for Linux.

But like you said:

> For using "su" in ADB, simply copy the original "su" file to somewhere like /data/local/tmp.

You are right, maybe my dissatisfaction will only be missed 😊

**Comment by RikkaW** [comment]
It's not about the number of commands, many things are impossible with only commands. I noticed you have a project that uses app_process. Have you tried using system server APIs that involving binder? You should know it is impossible to use them with only commands.

So I don't think the document is extreme 😋.

**Comment by gtf35** [comment]
You are right, many things can’t be done by commands, that is why I love this project so much.

When writing that project, I was inspired by [this article](https://haruue.moe/blog/2017/08/30/call-privileged-api-with-app-process/) to a large extent, but it’s a pity that I couldn’t finish it by binder at that time.

This is indeed the case, this project is great.

And the description of the document is appropriate.




Bye the way, when I see 「坏耶」, I know the author is related to Rikka.

But unfortunately the link that says "坏耶" at the beginning of the article cannot be opened

Only Chinese can express my feelings:
看完那篇文章我满脑子都是：「坏耶，坏耶，坏耶，坏耶...」，太魔性了。
感谢 Rikka 项目的每个成员，提供了那么多实用又黑科技的点子和贡献。
感谢 Rikka 项目陪伴我走过入门到成熟。😘

**Comment by RikkaW** [comment]
😋
