### ISSUE TITLE
装了最新模块12.1.3后导致设置查看应用使用内存时设置崩溃

### ISSUE THREAD

**Issue by duan-dky** [RikkaApps/Sui#14]
![Screenshot_20210830-114702](https://user-images.githubusercontent.com/74866582/131282410-225b6f67-2695-4109-a1d5-56b10b4557df.png)
打开任何一个应用设置都会闪退，降级为11.6版本后问题没有复现

**Comment by RikkaW** [comment]
更新到 12.1.4
