### ISSUE TITLE
既然已经有sui与riru了，可以整合一下。不再依赖magiak了。

### ISSUE THREAD

**Issue by user1121114685** [RikkaApps/Sui#15]
1.有更加规范的开发环境。
2.舍去了更加复杂的安装方式。
3.杜绝了不可控的bug产生。

**Comment by yujincheng08** [comment]
不依赖 magisk 怎么绕过 selinux？怎么挂载 so 到 system？

**Comment by RikkaW** [comment]
readme 里面第一段就写了

> To be clear, the full implementation of "root" is far more than "su" itself, there is a lot of hard work to be done before. Sui is not a full root solution, **it requires Magisk to run**.

**Comment by t3149** [comment]
2021年9月30日(木) 午前1:10 Rikka ***@***.***>:
