### ISSUE TITLE
[Zygisk] (276479e) (Module #62) Sui does not run properly

### ISSUE THREAD

**Issue by phorcys420** [RikkaApps/Sui#18]
Running https://github.com/RikkaApps/Sui/commit/276479e026496af1e521f7448dd87efdeae5a062 (https://github.com/RikkaApps/Sui/actions/runs/1421584576)

The "Sui" entry in the system settings, long-press menu just takes me to Internet properties. 

![Screenshot_20211105-074410](https://user-images.githubusercontent.com/57866459/140469517-b52740a9-897e-4713-9a37-e01fb8d898ed.png)

 #![Screenshot_20211105-074435](https://user-images.githubusercontent.com/57866459/140469526-05ebf8a3-4fb3-4ce8-8efe-6a94ebc524c8.png)

I can see that Sui's post-fs-data.sh has ran from the [magisk log](https://github.com/RikkaApps/Sui/files/7481161/magisk_log_2021-11-05T07_46_24Z.log).

Apps that use Shizuku (WADB in this case) prompt me using the usual MagiskSU prompt and not Sui's.

/data/adb/sui exists and there are two files that are in it (sui.db & sui.db-journal), sui.db-journal is blank.

Magisk log: https://github.com/RikkaApps/Sui/files/7481161/magisk_log_2021-11-05T07_46_24Z.log

**Comment by RikkaW** [comment]
1. Use debug version of Sui
2. Magisk log does not help, please provide full boot log

**Comment by phorcys420** [comment]
I installed the debug version, but how do I obtain said boot log ? logcat and dmesg show nothing about sui

**Comment by RikkaW** [comment]
Upload the log you grabbed.

Capture boot log:
Start the logcat before the earliest logs are overwritten, so that each log can be captured. Set log buffer size to maximum, so you don't have to start logcat at the beginning. Or you can use some Magisk module which runs logcat in post-fs-data.sh.

**Comment by phorcys420** [comment]
Sorry for delayed response.
[logcat.log](https://github.com/RikkaApps/Sui/files/7488606/logcat.log)

**Comment by RikkaW** [comment]
It seems that the Zygisk's companion is not working (no logs like `* Launching zygiskd64`), so it might be a Magisk issue.

Can you try again with the lastest Magisk CI build?

**Comment by phorcys420** [comment]
Latest Magisk CI build only proposes me to patch for commit d232cba0 which I am already running. Also I am using LSPosed Zygisk with no issues.

**Comment by RikkaW** [comment]
After a quick look at Magisk's source code, I can confirm that it is a problem of Maigsk.

**Comment by phorcys420** [comment]
What should I do then ? Also why does LSPosed run fine with zygisk ?

**Comment by RikkaW** [comment]
Wait for Magisk to fix it.

LSPosed uses the companion at a different time. Don't say why not change the timing, Sui does follow the document of Zygisk.

**Comment by phorcys420** [comment]
I see, thanks for the heads up.

**Comment by Gong-Mi** [comment]
> 等待马吉斯克修复它。
> 
> LSPosed 在不同的时间使用同伴。别说为什么不改变时间， 苏确实遵循了齐吉斯克的文件。
貌似用过riru版本就可以用zy版本

Looks like after you use riru, you can 
[magisk_log_2021-11-06T19_01_32Z.log](https://github.com/RikkaApps/Sui/files/7490304/magisk_log_2021-11-06T19_01_32Z.log)

**Comment by Gong-Mi** [comment]
> > 等待马吉斯克修复它。
> > 
> > LSPosed 在不同的时间使用同伴。别说为什么不改变时间， 苏确实遵循了齐吉斯克的文件。
> 貌似用过riru版本就可以用zy版本
> 
> Looks like after you use riru, you can 
> [magisk_log_2021-11-06T19_01_32Z.log](https://github.com/RikkaApps/Sui/files/7490304/magisk_log_2021-11-06T19_01_32Z.log)
> 

只是缓存

Okay, it's just a cache

**Comment by RikkaW** [comment]
Just learned that `zygiskd` is shared by all modules. So it is possible that LSPosed breaks `zygiskd`. Try to disable LSPosed?

**Comment by Gong-Mi** [comment]
> ~刚刚得知，所有模块都共享`了 zygiskd。`因此，有可能，LSPosed打破`齐吉斯克德`。尝试禁用 LSPosed？~没关系， 约翰 · 吴证实这是马吉斯克的错。

23013 ok Seems normal

**Comment by phorcys420** [comment]
> ~Just learned that `zygiskd` is shared by all modules. So it is possible that LSPosed breaks `zygiskd`. Try to disable LSPosed?~ Never mind, john wu confirmed it's Magisk's fault.

Indeed.
23013: Disabling LSposed makes Sui run properly
23014: Both LSPosed and Sui work
Closing this issue.
