### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by wzy19950000** [RikkaApps/Sui#20]
Redmi 10X Pro
MIUI V11.0.5
Magisk21.4
Riru v25.4.4
Redownloaded many times but still failed

The magisk installation log is as follow

- Copying zip to temp directory
- Installing sui-v12.2.1-release.zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
mkdir: can't create directory '/data/adb/sui': File exists
**********
 Sui 
 by Rikka 
**********
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: riru.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: riru.sh.sha256sum
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop.sha256sum
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: post-fs-data.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: post-fs-data.sh.sha256sum
- Device platform: arm64
- Extracting verify.sh
- Verified riru.sh
- Load /sbin/.magisk/modules/riru-core/util_functions.sh
- Riru: v25.4.4.r426.05efc94 (API 25)
- Installing from Magisk app
- Extracting module files
- Verified module.prop
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: uninstall.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: uninstall.sh.sha256sum
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: sepolicy.rule
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: sepolicy.rule.sha256sum
- Verified post-fs-data.sh
- Verified uninstall.sh
- Verified sepolicy.rule
- Extracting arm libraries
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libsui.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libsui.so.sha256sum
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libsui.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libsui.so.sha256sum
- Verified lib/armeabi-v7a/libsui.so
- Extracting arm64 libraries
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libmain.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libmain.so.sha256sum
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libadbd_wrapper.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libadbd_wrapper.so.sha256sum
- Verified lib/arm64-v8a/libsui.so
- Verified lib/arm64-v8a/libmain.so
- Verified lib/arm64-v8a/libadbd_wrapper.so
unzip: can't change directory to '/data/adb/modules_update/riru-sui/lib': No such file or directory
*********************************************************
! lib/arm64-v8a/libadbd_preload.so not exists
! This zip may be corrupted, please try downloading again
*********************************************************
! Installation failed

**Comment by wzy19950000** [comment]
> The lastest CI version should work

i'm sorry to bother again but what does CI means?

**Comment by RikkaW** [comment]
CI means continuous integration

https://github.com/RikkaApps/Sui/actions/runs/1524387314

**Comment by wzy19950000** [comment]
> CI means continuous integration
> 
> https://github.com/RikkaApps/Sui/actions/runs/1524387314

flashed successfully by magisk but phone crashed after reboot
took more time to boot and all application except syetem setting unavaliable (no respond clicking) .Navigation Bar and magisk manager also crashed. is there an zip pack cound be flashed by TWRP to recall all modification made by lastest CI.

and is there any log that could be helpful for you? maybe i can extract it by fastboot or recovery.

**Comment by RikkaW** [comment]
Considering you are using Riru 25, it's highly possible that you are using EdXposed.

[#](https://github.com/RikkaApps/Sui/issues/9#issuecomment-819160532)

> EdXposed is already a dead project from few months ago since all its real maintainers have moved to their own project LSPosed. Also, the quality of EdXposed is terrible, it has broken Sui for other reasons before. No one should use EdXposed anymore.

**Comment by wzy19950000** [comment]
> Considering you are using Riru 25, it's highly possible that you are using EdXposed.
> 
> [#9 (comment)](https://github.com/RikkaApps/Sui/issues/9#issuecomment-819160532)
> 
> > EdXposed is already a dead project from few months ago since all its real maintainers have moved to their own project LSPosed. Also, the quality of EdXposed is terrible, it has broken Sui for other reasons before. No one should use EdXposed anymore.
i think that's the reason, many thanks for your reply.
