### ISSUE TITLE
为什么输入*#*#784784#*#*打开的是wifi界面

### ISSUE THREAD

**Issue by Aditems** [RikkaApps/Sui#21]

**Comment by RikkaW** [comment]
说明 Sui 没有工作正常。
已知早已停止更新的 EdXposed 所使用的一个库有问题会导致 Sui 不能工作，如果有在使用建议换用其他的 Xposed 实现。

**Comment by Aditems** [comment]
现在使用的是lsposed，还有可能事甚么原因呢

**Comment by RikkaW** [comment]
提供开机 log（

**Comment by Aditems** [comment]
[logcat.txt](https://github.com/RikkaApps/Sui/files/7826054/logcat.txt)

**Comment by terrytw** [comment]
同楼主
长按设置按钮后点击sui进入wifi界面

**Comment by RikkaW** [comment]
@Aditems 需要的是正经的开机 log 而不是随便一小段不知道什么东西

**Comment by RikkaW** [comment]
@Aditems 更新了 12.4.0，如果你之前还是用的 12.2.1 那很可能你的不知道什么问题早就被修好了（
