### ISSUE TITLE
删除sui后长按设置的菜单未被删除

### ISSUE THREAD

**Issue by terrytw** [RikkaApps/Sui#22]
如题，安装sui后删除，长按设置的快速菜单里的sui依然存在

**Comment by RikkaW** [comment]
暂时需要手动清除设置的数据。真正的设置不会被清除，因为真正的设置存储在 com.android.providers.settings 而不是 com.android.settings。

**Comment by naniccc** [comment]
> 暂时需要手动清除设置的数据。真正的设置不会被清除，因为真正的设置存储在 com.android.providers.settings 而不是 com.android.settings。

![Screenshot_2024-03-22-22-49-10-82_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/RikkaApps/Sui/assets/57870281/686471b0-e959-4766-8003-3292f4b0253f)
如图清除数据是灰的，应该怎么删除sui的shortcut？
