### ISSUE TITLE
Just a question - after installing Sui, can I delete the SU binary to avoid detection?

### ISSUE THREAD

**Issue by vegedreamgagnoa** [RikkaApps/Sui#25]
Hey @RikkaW thanks for such amazing project. Everything works perfectly on my device.
Just a question, can I delete the SU binary to avoid detection? Many apps trying to detect root by executing "which su" command - and instead of renaming it I would like to delete the executable entirely to avoid detection.

What do you think?

**Comment by RikkaW** [comment]
Yes you can, but detecting root is far more than check if "su" exists.

In avoiding the detection side, the biggest advantage of Sui is it does not require a manager app (there are already apps that can detect hidden Magisk app) and "su" binary. This is one part of avoiding detection, not the whole.
