### ISSUE TITLE
授权弹窗不显示

### ISSUE THREAD

**Issue by Kazurin-775** [RikkaApps/Sui#28]
- 设备：小米平板 5 (nabu)
- 系统：MIUI 13.0.5, Android 11
- Sui: v12.4.0 release + Zygisk
- Magisk: 24.1

在 [WADB](https://github.com/RikkaApps/WADB) 中点击启动「无线 adb」之后，对应菜单项置灰，但是授权弹窗不显示。必须手动在 Sui 管理器中设置成「允许」之后才能授权成功。

![Screenshot_2022-02-15-13-35-31-963_moe haruue wadb](https://user-images.githubusercontent.com/71819243/153999299-12a7b891-545c-447b-a44f-ef041e670073.jpg)

[MaterialFiles](https://github.com/zhanghai/MaterialFiles) 同理，打开「根目录」之后无限转圈，需要手动授权。

相关日志：

```
02-15 13:41:48.406  4083  4328 E Logger  : No available log folder
02-15 13:41:48.691  2784  3102 D GestureInputHelper: onInputEvent action=0
02-15 13:41:48.691  2784  3102 W RecentsModel: getRunningTaskContainHome
02-15 13:41:48.699  2784  3102 D GestureInputHelper: onInputEvent, lastGestureMode=com.miui.home.recents.GestureModeHome@dc36ea8, newGestureMode=com.miui.home.recents.GestureModeApp@2887be0
02-15 13:41:48.700  2784  3073 E StateBroadcastUtils: sendFsStateBroadCast state=taskSnapshot   channel=gesture
02-15 13:41:48.722  2784  3102 D GestureInputHelper: onInputEvent action=1
02-15 13:41:48.722  2784  3102 D GestureTouchEventTracker: stopTailCatcher
02-15 13:41:48.722  2784  3102 D GestureTouchEventTracker: mUpType=10
02-15 13:41:48.733   820  1212 E Service : manager is null
```

查看 PID 820 的命令行，可以确认是 Sui 守护进程：

```
nabu:/ $ cat /proc/820/cmdline
sui
```

**Comment by RikkaW** [comment]
提供完整的开机 log（或者杀掉一次 system UI 期间的）

**Comment by Kazurin-775** [comment]
[logcat-coldboot.txt](https://github.com/RikkaApps/Sui/files/8076987/logcat-coldboot.txt)

[logcat-kill-systemui.txt](https://github.com/RikkaApps/Sui/files/8076988/logcat-kill-systemui.txt)

**Comment by RikkaW** [comment]
先重装一个最新的 CI 版本看看吗（

https://github.com/RikkaApps/Sui/actions 这里选一个最新的

**Comment by Kazurin-775** [comment]
刷了 12.5.0-release 之后就正常了，谢谢 :)
