### ISSUE TITLE
Sui and Shizuku running at the same time?

### ISSUE THREAD

**Issue by Jnss98b** [RikkaApps/Sui#29]
Should I uninstall shizuku if I installed sui (and vice versa) or they can safely run together on the same device? If not, is it recommended to use one over another?

**Comment by RikkaW** [comment]
First of all, they can run at the same time.

Sui does not support super old apps that lack Shizuku API v11+ support. If all your apps support Shizuku API v11+ and do not intentionally not supporting Sui (yes, there is such app), you can uninstall Shizuku.

**Comment by Jnss98b** [comment]
@RikkaW How would I check which version of the shuzuku api an app support?

**Comment by RikkaW** [comment]
Unfortunately, there is no way but to run the app.
