### ISSUE TITLE
Fail to install for Version lower than V22

### ISSUE THREAD

**Issue by diassynthesis** [RikkaApps/Sui#3]
Adding version number required for installation in the error message: V22 or above.(see attached images).
![Screenshot_2021-02-13_203600](https://user-images.githubusercontent.com/3822648/107860366-51d76e00-6e3f-11eb-9aec-da8850021c2f.gif) 
![Screenshot_2021-02-13_203806](https://user-images.githubusercontent.com/3822648/107860394-6451a780-6e3f-11eb-9030-1e337056b269.jpg)

Also, need detecting the version number installed and display it (For versions < 22).
Specify in the README.md file (by adding a Section REQUIRED):Need (version >= 22).

**Comment by RikkaW** [comment]
> Also, need detecting the version number installed and display it (For versions < 22).
> Specify in the README.md file (by adding a Section REQUIRED):Need (version >= 22).

Since every module should have moved to v22+ for long, anything involving pre-v22 is meaningless.
