### ISSUE TITLE
Add new Magisk auto-update support

### ISSUE THREAD

**Issue by rodrigoswz** [RikkaApps/Sui#32]
With Magisk v24, Modules Repo is dead, making harder to find and update our favorite modules.

Fortunately, topjohnwu introduced a new way to update Magisk Modules using Magisk App. But the developers need to add this individually for each module.

Could you add support to this to Sui?

**Comment by KieronQuinn** [comment]
Looks like it was already added in f8eee8c8c832b04ceac3ad41fb98f14266fd3e4d
