### ISSUE TITLE
Sui在LG设备上无法进入管理界面

### ISSUE THREAD

**Issue by ahetor** [RikkaApps/Sui#36]
本人是韩版U+的LG V50 ThinQ，面具版本为25.1，LSPose版本为1.8.3 (6581) - Zygisk，安卓10。在安装了sui-zygisk-v12.6.3模块后，无法正常进入管理界面，但可以对App Ops等进行授权。 通过拨号和快捷方式进入的是关于手机页面。
PS：这里附上开机日志文件（不知道对不对）
[data_app_anr@1656759065495.txt.gz](https://github.com/RikkaApps/Sui/files/9034207/data_app_anr%401656759065495.txt.gz)

**Comment by ahetor** [comment]
[anr_2022-07-02-18-50-45-076.zip](https://github.com/RikkaApps/Sui/files/9034219/anr_2022-07-02-18-50-45-076.zip)

**Comment by RikkaW** [comment]
这不是开机 log

**Comment by ahetor** [comment]
抱歉，我去查了一下怎么抓，在下面了
[logcat_E_2022-0704.log](https://github.com/RikkaApps/Sui/files/9036078/logcat_E_2022-0704.log)
[logcat_V_2022-0704.log](https://github.com/RikkaApps/Sui/files/9036079/logcat_V_2022-0704.log)

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Sui/actions/runs/2469484869
从这里取一个 debug 版本的再来。然后开始 logcat 太晚了，刚开机的部分不见了（开发者设置里 log 缓冲区大小设置为最大也行），再然后上面的 log 似乎是没有进行打开快捷方式等操作时抓取的。

**Comment by ahetor** [comment]
已使用debug版本抓取，日志如下。
[logcat_V_20220704-1812.log](https://github.com/RikkaApps/Sui/files/9038630/logcat_V_20220704-1812.log)
PS：附带一张授权界面。
![Screenshot_20220704-182638](https://user-images.githubusercontent.com/64998460/177137031-5269c23a-e7de-413a-81e8-86214dce0583.png)

**Comment by RikkaW** [comment]
还是没能从 log 中看出有在开始抓取 log 前进行“通过拨号和快捷方式进入的是关于手机页面”这样的操作。

**Comment by ahetor** [comment]
这我就不太清楚了，我确实是进行了以上操作后进行抓取的，可能是体质原因吧，也许以后修着修着就好了。抱歉，占用了你的时间。

**Comment by RikkaW** [comment]
虽然但是，你的 log 好像体现了你的主屏幕应用不是默认的，如果换回默认的试一下呢（
