### ISSUE TITLE
在其他终端中运行rish不起作用

### ISSUE THREAD

**Issue by DevilDisguise** [RikkaApps/Sui#38]
已按照post-install.example.sh的说明，导出sui.dex/librish.so/rish三个文件到其他终端(例如Termux)的数据目录中，并移动到环境变量中，同时Sui给予授权，但此时运行"rish"仍然不起作用，返回"killed"。

**Comment by RikkaW** [comment]
看一下 log（直接在 Termux 里运行一下 logcat 应该就有了）

**Comment by DevilDisguise** [comment]
> 看一下 log（直接在 Termux 里运行一下 logcat 应该就有了）

--------- beginning of main
07-16 20:33:38.476 18266 18266 I libc    : SetHeapTaggingLevel: tag level set to 0
07-16 20:33:38.506 18266 18266 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
07-16 20:33:38.524 18266 18266 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10158; state: DISABLED
07-16 20:33:38.533 18266 18266 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
07-16 20:33:38.612 18266 18266 V GraphicsEnvironment: ANGLE Developer option for 'com.termux' set to: 'default'
07-16 20:33:38.612 18266 18266 V GraphicsEnvironment: ANGLE GameManagerService for com.termux: false
07-16 20:33:38.612 18266 18266 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
07-16 20:33:38.613 18266 18266 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-16 20:33:38.614 18266 18266 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-16 20:33:38.653 18266 18266 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10158; state: ENABLED
07-16 20:33:38.685 18266 18302 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
07-16 20:33:38.685 18266 18302 D MediaCodecList: codecHandlesFormat: no format, so no extra checks
07-16 20:33:38.686 18266 18303 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
07-16 20:33:38.689 18266 18303 I OMXClient: IOmx service obtained
07-16 20:33:38.698 18266 18266 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10158; state: DISABLED
07-16 20:33:38.749 18266 18297 I AdrenoGLES: QUALCOMM build                   : aabe7e1, I5a11487fec
07-16 20:33:38.749 18266 18297 I AdrenoGLES: Build Date                       : 09/28/20
07-16 20:33:38.749 18266 18297 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.10
07-16 20:33:38.749 18266 18297 I AdrenoGLES: Local Branch                     : mybrancheb01a6f9-5f18-f1ba-bc90-ac1f6bcc2cee
07-16 20:33:38.749 18266 18297 I AdrenoGLES: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r104-rel
07-16 20:33:38.749 18266 18297 I AdrenoGLES: Remote Branch                    : NONE
07-16 20:33:38.749 18266 18297 I AdrenoGLES: Reconstruct Branch               : NOTHING
07-16 20:33:38.749 18266 18297 I AdrenoGLES: Build Config                     : S L 8.0.12 AArch64
07-16 20:33:38.756 18266 18297 I AdrenoGLES: PFP: 0x005ff112, ME: 0x005ff066
07-16 20:33:38.788 18266 18322 I Gralloc4: mapper 4.x is not supported
07-16 20:33:38.790 18266 18322 W Gralloc3: mapper 3.x is not supported
07-16 20:33:38.793 18266 18322 W Gralloc4: allocator 4.x is not supported
07-16 20:33:38.793 18266 18322 W Gralloc3: allocator 3.x is not supported
07-16 20:33:38.794 18266 18322 I Gralloc2: Adding additional valid usage bits: 0x202000
07-16 20:33:38.825 18266 18266 W com.termux: type=1400 audit(0.0:97): avc: granted { execute } for name="login" dev="mmcblk0p64" ino=26994 scontext=u:r:untrusted_app_27:s0:c158,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c158,c256,c512,c768 tclass=file app=com.termux
07-16 20:33:38.848 18266 18266 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10158; state: DISABLED
07-16 20:33:38.845 18349 18349 W com.termux: type=1400 audit(0.0:98): avc: granted { execute } for name="login" dev="mmcblk0p64" ino=26994 scontext=u:r:untrusted_app_27:s0:c158,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c158,c256,c512,c768 tclass=file app=com.termux
07-16 20:33:38.845 18349 18349 W com.termux: type=1400 audit(0.0:99): avc: granted { execute_no_trans } for path="/data/data/com.termux/files/usr/bin/login" dev="mmcblk0p64" ino=26994 scontext=u:r:untrusted_app_27:s0:c158,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c158,c256,c512,c768 tclass=file app=com.termux
07-16 20:33:38.845 18349 18349 W com.termux: type=1400 audit(0.0:100): avc: granted { execute } for name="dash" dev="mmcblk0p64" ino=27217 scontext=u:r:untrusted_app_27:s0:c158,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c158,c256,c512,c768 tclass=file app=com.termux
07-16 20:33:38.862 18349 18349 W login   : type=1400 audit(0.0:101): avc: granted { execute } for path="/data/data/com.termux/files/usr/bin/dash" dev="mmcblk0p64" ino=27217 scontext=u:r:untrusted_app_27:s0:c158,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c158,c256,c512,c768 tclass=file app=com.termux
07-16 20:33:38.879 18363 18363 W login   : type=1400 audit(0.0:102): avc: granted { execute } for name="coreutils" dev="mmcblk0p64" ino=27317 scontext=u:r:untrusted_app_27:s0:c158,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c158,c256,c512,c768 tclass=file app=com.termux
07-16 20:33:38.879 18363 18363 W login   : type=1400 audit(0.0:103): avc: granted { execute_no_trans } for path="/data/data/com.termux/files/usr/bin/coreutils" dev="mmcblk0p64" ino=27317 scontext=u:r:untrusted_app_27:s0:c158,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c158,c256,c512,c768 tclass=file app=com.termux
07-16 20:33:39.007 18266 18266 D InputMethodManager: showSoftInput() view=com.termux.view.TerminalView{7785ee4 VFED.V.L. .F...... 0,0-1064,1885 #7f080191 app:id/terminal_view aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
07-16 20:33:39.065 18266 18266 D InsetsController: show(ime(), fromIme=true)
07-16 20:33:39.205 18266 18266 D InputMethodManager: showSoftInput() view=com.termux.view.TerminalView{7785ee4 VFED.V.L. .F...... 0,0-1064,1052 #7f080191 app:id/terminal_view aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
07-16 20:33:39.218 18266 18266 D InsetsController: show(ime(), fromIme=true)
07-16 20:33:40.865 18266 18297 E cutils-trace: Error opening trace file: No such file or directory (2)
07-16 20:33:41.122 18464 18464 W bash    : type=1400 audit(0.0:138): avc: granted { execute } for name="rish" dev="mmcblk0p64" ino=134135 scontext=u:r:untrusted_app_27:s0:c158,c256,c512,c768 tcontext=u:object_r:app_data_file:s0 tclass=file app=com.termux
07-16 20:33:41.122 18464 18464 W bash    : type=1400 audit(0.0:139): avc: granted { execute } for name="rish" dev="mmcblk0p64" ino=134135 scontext=u:r:untrusted_app_27:s0:c158,c256,c512,c768 tcontext=u:object_r:app_data_file:s0 tclass=file app=com.termux
07-16 20:33:41.122 18464 18464 W bash    : type=1400 audit(0.0:140): avc: granted { execute_no_trans } for path="/data/data/com.termux/files/usr/bin/rish" dev="mmcblk0p64" ino=134135 scontext=u:r:untrusted_app_27:s0:c158,c256,c512,c768 tcontext=u:object_r:app_data_file:s0 tclass=file app=com.termux
07-16 20:33:41.129 18464 18464 W rish    : type=1400 audit(0.0:141): avc: granted { execute } for path="/data/data/com.termux/files/usr/lib/libtermux-exec.so" dev="mmcblk0p64" ino=26714 scontext=u:r:untrusted_app_27:s0:c158,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c158,c256,c512,c768 tclass=file app=com.termux
07-16 20:33:41.132 18465 18465 W rish    : type=1400 audit(0.0:142): avc: granted { execute } for name="coreutils" dev="mmcblk0p64" ino=27317 scontext=u:r:untrusted_app_27:s0:c158,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c158,c256,c512,c768 tclass=file app=com.termux
07-16 20:33:41.353 18466 18466 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10158 <<<<<<
07-16 20:33:41.359 18466 18466 I AndroidRuntime: Using default boot image
07-16 20:33:41.359 18466 18466 I AndroidRuntime: Leaving lock profiling enabled
07-16 20:33:41.359 18466 18466 W libc    : Access denied finding property "odsign.verification.success"
07-16 20:33:41.360 18466 18466 E cutils-trace: Error opening trace file: No such file or directory (2)
07-16 20:33:41.363 18466 18466 W rish    : ART APEX data files are untrusted.
07-16 20:33:41.363 18466 18466 I rish    : Core platform API reporting enabled, enforcing=false
07-16 20:33:41.479 18466 18466 D rish    : Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
07-16 20:33:41.479 18466 18466 D rish    : I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt68l.dat
07-16 20:33:41.522 18466 18466 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
07-16 20:33:41.522 18466 18466 D AndroidRuntime: Calling main entry rikka.sui.shell.Shell
07-16 20:33:41.533 18466 18466 I ShizukuApplication: attachApplication
07-16 20:33:41.538 18466 18466 D hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
07-16 20:33:41.538 18466 18466 D AndroidRuntime: Shutting down VM
--------- beginning of crash
07-16 20:33:41.538 18466 18466 E AndroidRuntime: FATAL EXCEPTION: main
07-16 20:33:41.538 18466 18466 E AndroidRuntime: PID: 18466
07-16 20:33:41.538 18466 18466 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "librish.so" not found
07-16 20:33:41.538 18466 18466 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
07-16 20:33:41.538 18466 18466 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
07-16 20:33:41.538 18466 18466 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1656)
07-16 20:33:41.538 18466 18466 E AndroidRuntime: 	at rikka.sui.h0.a(SourceFile:2)
07-16 20:33:41.538 18466 18466 E AndroidRuntime: 	at rikka.sui.s0.run(SourceFile:5)
07-16 20:33:41.538 18466 18466 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-16 20:33:41.538 18466 18466 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-16 20:33:41.538 18466 18466 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-16 20:33:41.538 18466 18466 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-16 20:33:41.538 18466 18466 E AndroidRuntime: 	at rikka.sui.shell.Shell.main(SourceFile:19)
07-16 20:33:41.538 18466 18466 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-16 20:33:41.538 18466 18466 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
07-16 20:33:41.539 18466 18466 E AndroidRuntime: Error reporting crash
07-16 20:33:41.539 18466 18466 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
07-16 20:33:41.539 18466 18466 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
07-16 20:33:41.539 18466 18466 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:571)
07-16 20:33:41.539 18466 18466 E AndroidRuntime: 	at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:416)
07-16 20:33:41.539 18466 18466 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
07-16 20:33:41.539 18466 18466 E AndroidRuntime: 	at android.os.ServiceManager.rawGetService(ServiceManager.java:335)
07-16 20:33:41.539 18466 18466 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:134)
07-16 20:33:41.539 18466 18466 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4437)
07-16 20:33:41.539 18466 18466 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4434)
07-16 20:33:41.539 18466 18466 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:43)
07-16 20:33:41.539 18466 18466 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:4425)
07-16 20:33:41.539 18466 18466 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:156)
07-16 20:33:41.539 18466 18466 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
07-16 20:33:41.539 18466 18466 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
07-16 20:33:41.539 18466 18466 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)
07-16 20:33:41.539 18466 18466 I Process : Sending signal. PID: 18466 SIG: 9

**Comment by RikkaW** [comment]
> dlopen failed: library "librish.so" not found

> 已按照post-install.example.sh的说明

你这个说法听起来像是自己去复制文件的（

**Comment by DevilDisguise** [comment]
> > dlopen failed: library "librish.so" not found
> 
> > 已按照post-install.example.sh的说明
> 
> 你这个说法听起来像是自己去复制文件的（

不是，执行的脚本，把注释掉的改了改，当然实际执行的操作也就是改rish中的包名、改权限、复制文件。

**Comment by DevilDisguise** [comment]
> > dlopen failed: library "librish.so" not found
> 
> > 已按照post-install.example.sh的说明
> 
> 你这个说法听起来像是自己去复制文件的（

当然最后是手动转移到环境变量目录(/usr/bin，/usr/lib)中的，也试过不转移直接执行"rish"，依然报错

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Sui/blob/352e70efc0c6d341aeec7b3e76b36a55f4cbacf2/template/magisk_module/rish#L11

> DEX="$BASEDIR"/rish.dex
> ...
> -Djava.library.path="$BASEDIR"
> -Djava.class.path="$DEX"

假定了 rish.dex 和 librish.so 是和 rish 放一起的，所以 rish 本身也要连着改。

**Comment by DevilDisguise** [comment]
发现在国内定制系统(EMUI9.1,Android 9)上，Sui(12.6.3)的rish shell在Termux中不起作用，日志如下：
08-06 18:43:13.165  7085  7085 I appproc : Command=/system/bin/app_process -Djava.class.path=/data/data/com.termux/files/usr/bin/rish.dex -Djava.library.path=/data/data/com.termux/files/usr/bin /system/bin --nice-name=rish rikka.sui.shell.Shell

08-06 18:43:13.221  7085  7085 I rish    : The ClassLoaderContext is a special shared library.

08-06 18:43:13.222  7085  7085 I rish    : Reinit property: dalvik.vm.checkjni= false

08-06 18:43:13.244  7085  7085 E rish    : No implementation found for long android.util.HwEtrace.etrace_get_tls_id_and_new_span_for_caller_native(int) (tried Java_android_util_HwEtrace_etrace_1get_1tls_1id_1and_1new_1span_1for_1caller_1native and Java_android_util_HwEtrace_etrace_1get_1tls_1id_1and_1new_1span_1for_1caller_1native__I)

同时，Shizuku(12.8.1)的rish shell经测试可以正常使用

**Comment by DevilDisguise** [comment]
@RikkaW

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Sui/runs/7721056102 尝试这个构建。
