### ISSUE TITLE
Problem with Sui in tablets running A12L+

### ISSUE THREAD

**Issue by rodrigoswz** [RikkaApps/Sui#41]
It took me a long time to find out that it was Sui was causing this problem, and it's even a little tricky to explain...
With Sui module enable/installed, opening Settings intents is buggy on tablets running A12L+.

In the screen recording below, when opening App Info page **without Sui**, "Settings dual panel" opens normally with _App Info_ on the right and Settings categories on the left.

https://user-images.githubusercontent.com/14058427/190726207-c8aac6b1-61eb-4bb0-86b4-821c5565e0cd.mp4

But notice what happens when **Sui is enabled**: Settings is opened completely with the first category selected (Network and Internet) and using back gesture is displayed _App Info_ page stretched.

https://user-images.githubusercontent.com/14058427/190726232-6f132778-c350-4d78-9c57-61c8a840cbf6.mp4

This happens with literally any shortcut that launches some page in the settings. App Info from launcher was just the example used in the video.

**Comment by RikkaW** [comment]
This build should solve your problem. https://github.com/RikkaApps/Sui/actions/runs/3176392726

**Comment by rodrigoswz** [comment]
Yes! I can confirm, this build fixed the problem.

Thank you very much 😁
