### ISSUE TITLE
Noop question here, as a magisk user I don't know if I should or should not use this module

### ISSUE THREAD

**Issue by 5wHN28Dg** [RikkaApps/Sui#49]
Would I benefit from using it? How do I exactly use it? What are the benefits to the user if any?

**Comment by badbanii** [comment]
@5wHN28Dg Hi, this is an alternative for Shizuku.

**Comment by HarriBuh** [comment]
@5wHN28Dg Try this article, it helped me a lot to understand: https://www.xda-developers.com/shizuku/#installshizukuroot
