### ISSUE TITLE
v11.6.0 causes bootloop

### ISSUE THREAD

**Issue by petmarb** [RikkaApps/Sui#6]
on op6t with latest os, magisk, latest riru core + some other modules installed, updating sui to v. 11.6.0 causes reproducable bootloops.
reinstalling v11.5.0 solved the problem

**Comment by RikkaW** [comment]
No log 🙃

**Comment by admzzz** [comment]
same problem on los 17.2 with magisk 22.0 and riru 25.3.3

**Comment by petmarb** [comment]
yeah, I know, meaning I don't know how to get the logfile within a 
bootloop, because I had to delete the module within twrp and re-install the 
version before.
just wanted to let you know.

Am 24. März 2021 14:52:23 schrieb Rikka ***@***.***>:

**Comment by admzzz** [comment]
RikkaW ,
 does  11.6.0 require Shizuku to be installed, or it can function without it?

**Comment by RikkaW** [comment]
Connect to a computer and use adb logcat, adb should be available in this type of "bootloop".
Or use Magisk module to run logcat in post-fs-data.

**Comment by admzzz** [comment]
[sui_logcat.txt.zip](https://github.com/RikkaApps/Sui/files/6213255/sui_logcat.txt.zip)
here it is. 
after deleting v11.6.0 from /data/adb/modules phone starts fine.

**Comment by RikkaW** [comment]
@admzzz

`com.android.settings` crash at the end, is the only thing suspicious. However, no dump since MagiskHide is enabled. Please disable MagiskHide and do logcat again.

Additionally, I found EdXposed, EdXposed is ridiculously low quality 🙃. The crash is right after EdXposed. Need the log to confirm.

```
03-26 19:48:52.349  4149  4149 I EdXposed: Riru hooks installed
03-26 19:48:52.352  2023  2023 I NetworkStackClient: Network stack service connected
03-26 19:48:52.352  4128  4128 I EdXposed: Loading modules for com.qualcomm.qti.telephonyservice
03-26 19:48:52.353  4128  4128 I EdXposed-Bridge: Loading modules from /data/app/ru.YVKJNCuv.XNrCIyCEb-8OAGlypuQuh0ZjzIZ_jg4w==/base.apk
03-26 19:48:52.353  3769  3769 W ndroid.systemu: Unsupported class loader
03-26 19:48:52.354  4149  4149 F libc    : Fatal signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0x7464ba8000 in tid 4149 (ndroid.setting), pid 4149 (ndroid.setting)
```

**Comment by admzzz** [comment]
@RikkaW ,
[sui.txt.zip](https://github.com/RikkaApps/Sui/files/6214874/sui.txt.zip)
you were right about com.android settings: after switching off MagiskHide phone boots (almost) normally - with crashed settings' app (look at the screenshot).

**Comment by yujincheng08** [comment]
Disabling EdXposed should work.

**Comment by yujincheng08** [comment]
@admzzz 
You can have a test to LSPosed, which we test to work normally with lastest sui.

**Comment by admzzz** [comment]
@yujincheng08 ,
does LSPosed support all xposed's modules? is there any list of module's compatibility?

**Comment by yujincheng08** [comment]
@admzzz It supports all xposed modules that support EdXposed.

**Comment by admzzz** [comment]
@yujincheng08 
no way: all modules are not working due to "04-23 21:53:24.464  1067  1067 F art_apex: Device is not fsverity-enabled.".
![Screenshot_20210327-115948_LSPosed](https://user-images.githubusercontent.com/4542575/112716318-b08c0f00-8ef6-11eb-9385-8176eab0cca1.png)

**Comment by yujincheng08** [comment]
@admzz As shown: it's Magisk problem. Using the previous Magisk canary should fix it (not the latest because of https://github.com/topjohnwu/Magisk/issues/4098). And EdXposed also requires such sepolicies but it won't show warning but silently ignore it and letting system modules unloaded.

**Comment by admzzz** [comment]
@yujincheng08 ,
thank you kindly for your answers.
after downgrading to magisk 20005 lsposed works (though line " is not fsverity-enabled." is still in the log), but not all modules works properly with it (mimnminguard or appsettings reborn, for example), but when i switch to edxposed these not working modules works fine.
need time to check everything.

or maybe it would be better to downgrade to magisk 20003?

**Comment by petmarb** [comment]
LSPosed never ever worked on my device.
EdXpoded did always flawlessly and still does in it's latest version.
Also Magisk does it's job as expected, with no drama at all - besides the fact that in my opinion the new gui is somewhat useless and I would wish back the old one.
I don't think it's the right way to hit on many other things, when it is that simple, with downgrade to SUI 11.5.0 everything works again as before.
Updating again -> bootloop
So what?

**Comment by yujincheng08** [comment]
@admzzz You need to reinstall LSPosed after downgrading to 22005 because the sepolicies are already missed by Magisk.

**Comment by petmarb** [comment]
> @admzzz It supports all xposed modules that support EdXposed.

really? GravityBox? Since when?

**Comment by yujincheng08** [comment]
@petmarb Always working since 1.1.0. The devs of GravityBox also officially states it supports LSPosed. And EdXposed's YAHFA has a bug that prevents GravityBox from working on some devices with Android Q+.

**Comment by admzzz** [comment]
@yujincheng08 ,
after deleting lsposed, phone's restart and reinstallation it from repository, it's status is activated, but some modules still do not work.

**Comment by yujincheng08** [comment]
@admzzz As I said, it's EdXposed's issue and thus this issue is closed.

**Comment by admzzz** [comment]
@RikkaW , jfyi:
i'd updated magisk 22006 according to https://github.com/topjohnwu/Magisk/commit/aa020578955e0063aada2d618c6432faf92a0d33 and after installation of v11.6.0 got bootloop again.

so, the problem is not in (edxposed's) missing sepolicy rules for sure.

**Comment by admzzz** [comment]
@RikkaW , jfyi:
i'd updated magisk 22006 according to https://github.com/topjohnwu/Magisk/commit/aa020578955e0063aada2d618c6432faf92a0d33 and after installation of v11.6.0 got bootloop again.

so, the problem is not in (edxposed's) missing sepolicy rules for sure.

**Comment by yujincheng08** [comment]
we never said bootloop is caused by sepolicy. And the crash point is definitely from edxposed. Stop using it.

**Comment by RyanGamingXbox** [comment]
> @RikkaW , jfyi:
> i'd updated magisk 22006 according to [topjohnwu/Magisk@aa02057](https://github.com/topjohnwu/Magisk/commit/aa020578955e0063aada2d618c6432faf92a0d33) and after installation of v11.6.0 got bootloop again.
> 
> so, the problem is not in (edxposed's) missing sepolicy rules for sure, as v11.5.0 works fine.

This is totally because of EdXposed. I switched to LSPosed and it works. I don't get stuck in a bootloop anymore. So just shut up, and bite the bullet. You can test this by simply disabling EdXposed through your recovery.

**Comment by maxweisspoker** [comment]
In the other thread, [RikkaW mentioned](https://github.com/RikkaApps/Sui/issues/7#issuecomment-809882354) that this issue may crop up in future Riru modules.  What steps can the user take to avoid this?

**Comment by petmarb** [comment]
finally I found the time to give LSPosed another try in combination of all the other Riru modules, except for EdXpoded of course - rebooted, activated my beloved and very needed Xposed modules in LSPosed, rebooted again and ... what shall I say. besides the fact that now all Xposed modules work with no problem at all, I got an unbelievable dramatic speedboost all over the entire OS.
It looks like EdXposed was slowing down the system, which I didn't even know. so, thank you very much RikkaW, you were totally right: kick off EdXposed for LSPosed in exchange, update everything and fall in love with your device again, thanks to RikkaW's great work!

**Comment by Evengard** [comment]
Too bad LSposed devs don't want to implement global hooks for the modules which needs it... Ticking 100+ boxes for each module is making me insane.
...and I can't use EdXposed with Sui...

**Comment by petmarb** [comment]
that's not true. you don't have to tick hundreds of boxes. just mark the first, which should be the system framework to make the module work systemwide

**Comment by Evengard** [comment]
That was the first thing I've tried. Unfortunately that didn't work for ButteretToast Revived.

**Comment by mattfbacon** [comment]
Thanks so much for this; I had the same bootloop issue. Could you possibly add some kind of check for EdExposed in the install script to warn users of this bootloop?
