### ISSUE TITLE
Can't remove the shortcut in the menu of `Long press system settings from the home app`.

### ISSUE THREAD

**Issue by StellarH** [RikkaApps/Sui#65]
After I disabled the module in `Magisk`, the shortcut in the menu of `Long press system settings from the home app` will not be removed.
System Info:
MIUI14.0.29 on Xiaomi 13, based on Android 13 with security update 2023-05-01.

CN:
当我在`Magisk`中禁用这个模块时，长按设置菜单中的`Sui`入口将不会被删除。
系统信息:
小米13的MIUI14.0.29，基于带有2023-05-01安全修复补丁的Android 13。

**Comment by RikkaW** [comment]
清除”设置“应用的数据。真正的设置在”设置存储“（settings provider）里面，那个叫”设置“的只是 UI，所以不会有影响。

**Comment by StellarH** [comment]
清除之后，
`注视亮屏``双击亮屏``锁屏双击“音量-”启动相机``阳光屏`等设置重置
`色彩模式`UI重置

**Comment by StellarH** [comment]
还是稍微找点方法吧，国内一堆定制UI，谁知道会往哪个应用数据里写东西😂

**Comment by RikkaW** [comment]
那就是卸载时再运行一个自己的 dex，在里面实现移除快捷方式。但是好忙呀 撕不开了
