### ISSUE TITLE
Android 11 v11.6.0

### ISSUE THREAD

**Issue by BlueCat300** [RikkaApps/Sui#7]
Hello, there were problems after updating to version 11.6.0
The device freezes on the lock screen and does not even allow the device to be unlocked, but not the whole system is just the lock screen interface. Sometimes it allows you to unlock, but it still does not allow you to enter the system settings.

Latest working version 11.5.0 
Android 11 Samsung OneUI 3.1

I also have a samsung device with android 10 and OneUI 2.5 and 11.6.0 works fine there.
If you need any logs tell me how to get them without unlocking since device cannot be unlocked due to a bug.

**Comment by RikkaW** [comment]
Maybe it's similar to #6, if you have EdXposed, try disableing it.

**Comment by BlueCat300** [comment]
> Maybe it's similar to #6, if you have EdXposed, try disableing it.

Adding package **com.android.settings** to the edxposed blacklist solved the problem.
But it's still some kind of conflict between edxposed hooks and this module since 11.5.0 working good with same version edxposed.

**Comment by RikkaW** [comment]
It's not about Sui itself, but some kind of coincidence related to Dobby (EdXposed uses it) and the new hiding implementation of Riru v25 finally cause SIGBUS (from Dobby's code). If there are some other Riru module that adapts Riru v25, it's highly possible this same problem will happen.

**Comment by maxweisspoker** [comment]
> It's not about Sui itself, but some kind of coincidence related to Dobby (EdXposed uses it) and the new hiding implementation of Riru v25 finally cause SIGBUS (from Dobby's code). If there are some other Riru module that adapts Riru v25, it's highly possible this same problem will happen.

I understand this is the fault of EdXposed and/or Magisk, but you also say that other Riru modules may end up creating the same problem.

What advice would you give to a user who uses EdXposed and these other Riru modules and wishes to avoid this fate?

Should I simply stop updating all Riru-based modules?

As a user, it is semantics and unimportant to me where the blame lies, I simply want to ensure my phone works, and therefore my solution for this problem has been to install Riru-Sui 11.5.  It is desirable to have the most up-to-date modules, but that is a secondary concern to having my phone boot.  Therefore, should I downgrade Riru to v24 and never update Riru modules?

**Comment by RikkaW** [comment]
@maxweisspoker Simple switch to LSPosed, which does not have this problem.

**Comment by admzzz** [comment]
@maxweisspoker ,
i'd received the same advice  from @RikkaW two days ago, followed it and just happy (increased speed of booting and systemui is an additional benefit ;-) ).
