### ISSUE TITLE
Won't boot after magisk SUI installation

### ISSUE THREAD

**Issue by tazer4** [RikkaApps/Sui#9]
Moto G Power 2020 (sofia) running android 10 magisk with riru and edxposed (latest magisk repo versions).  Upon installing the version found here sui-v11.6.0.zip or the newer version from the magisk repo the phone will not boot past the motorolla logo, I am unable to capture any debug info or logcat with the debug version of sui.  I have to delete the module from recovery to boot again.

Any ideas what could be wrong and how to further investigate the issue?  Thanks.

**Comment by RikkaW** [comment]
It's EdXposed's issue (see #6).

EdXposed is already a dead project from few months ago since all its real maintainers have moved to their own project LSPosed. No one should use EdXposed.

**Comment by RikkaW** [comment]
@tazer4 The problem is on EdXposed side, nothing I can do.
